version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      working_dir: /var/www/html
      volume:
        - ../backend:/var/www/html
    ports:
      - 8080:8080
