version: '3.8'
services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:80
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ../back-end/softExpert-back:/var/www/html
    environment:
      - DB_HOST=DESKTOP-D7S7L2B
      - DB_PORT=1433
      - DB_NAME=MarketDB
      - DB_USER=admin
      - DB_PASSWORD=admin

  database:
    build:
      context: ../
      dockerfile: ./docker/DB.Dockerfile      
    environment:
      - SA_PASSWORD=E8d#s46i
    ports:
      - 1433:1433